### ISSUE TITLE
Add event location helper text

### ISSUE THREAD

**Issue by KGorr** [mozilla/clubs-events#20]
Suggestion:

Example: "North University Library" or "a friend's home"

**Comment by flukeout** [comment]
We just removed this field for now - not sure it's necessary if we have city & country. 

@KGorr is this info something you'd be interested in seeing & tracking? Reopen if so.

**Comment by KGorr** [comment]
Eh, I think it's fine without it. We'll likely find out this bit of info in the event details/photos. Thanks!
