### ISSUE TITLE
Add intro text above form

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/clubs-events#32]
via @KGorr 

> Tell us about the Mozilla Clubs event you hosted! The report will be available for others to browse. Remember, by submitting information on this form, you’re giving us permission to use in newsletters, blogs, and other marketing and training materials. 

cc @amirad

**Comment by xmatthewx** [comment]
cc @flukeout

**Comment by flukeout** [comment]
Done

**Comment by amirad** [comment]
Ekk can I edit this? It's great, just want to add a few tweeks. 

Congratulations on running a Mozilla Club event! Complete this report so we can hear how it went and share the information for others to browse (and be inspired!). Be sure to add as much information and links as you can, the more you add the easier it will be for others to visualize your event. 

We love sharing what's happening in the community through our newsletters, blogs, and other marketing and training materials. By completing this form you're giving us permission to share your wonderful work with the global community.

**Comment by xmatthewx** [comment]
@flukeout can you reopen this? (can you add mofo-teams to admin the repo? i can't triage.)

**Comment by flukeout** [comment]
@xmatthewx Added mofo-design, is there a mofo-catchall? Also @amirad you should be able to edit the form and matthew too now.

**Comment by xmatthewx** [comment]
I think that we usually assign `mofo-staffonly` to general access and `mofo-admin-staffonly` to admin access.

**Comment by amirad** [comment]
Thank you! I updated the form directly with my changes. Closing!
