### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by flukeout** [mozilla/clubs-events#33]
**Form**
- Should we validate the links that are provided blog posts, photo albums etc
- Should we ask what number of meeting this was for the club?
- Decide which fields are required in the form

**Reports**
- Which fields should we include in the publicly visible reports? All?
  - We might want to omit the Your Feedback question

**Comment by amirad** [comment]
Don't think we need to ask what number of meetings this was for - though is there a way we can track this in the backend? I've told Matthew this but ideally in the long-term we want to reward those who submit 10, 15, 20 event reports. 

We should definitely hide that last question. The others seem okay to include (though not all are mandatory).

**Comment by xmatthewx** [comment]
While we talk on Wednesday, let's try and shift all the conversation from the google doc to this thread or other github issues.

**Comment by flukeout** [comment]
Closing, as these questions have been answered
