### ISSUE TITLE
Finalize the initial version of the form.

### ISSUE THREAD

**Issue by flukeout** [mozilla/clubs-events#34]
We need to audit all of the questions and for each field decide...
- Is this question in the correct place in the form?
- Is this the right question label?
- Is helper text necessary, and if so, is this the right one?
- Should it be a required field?
- Should we validate this field?
  - We can do some basic validation on URLs
  - We can validate the attendance to make sure it's a number
  - We can have a minimum and maximum number of Web Literacies selected
- For the country field, should we place certain countries near the top of the dropdown? You can't search by typing, so might be annoying to have to use the full list.
- Some questions have **(Optional)** in the question, is that how we want to indicate optional responses?

We can go over this on Wednesday with @amirad

**Comment by flukeout** [comment]
Seems like we're happy with the form now.

**Comment by amirad** [comment]
so so so happy @flukeout @xmatthewx 
![Alt Text](https://media.giphy.com/media/t37LNokbw3M76/giphy.gif)
