### ISSUE TITLE
Explore ideas for showing images within the reporting tool.

### ISSUE THREAD

**Issue by flukeout** [mozilla/clubs-events#36]
Images are a powerful way to convey the feel of an event - how can we incorporate them?

One idea is to ask for a URL to an image that we can somehow use as the "cover" of a report. This will require some design work and we also need to accomodate reports without an image. We don't want things to look junky because only a few people have provided an image.

**Comment by flukeout** [comment]
Here's a concept. If the event report includes a cover photo, we include it in the event card but if it doesn't, we give it the treatment on the right...

![image](https://cloud.githubusercontent.com/assets/25212/14837257/8bb1d7ea-0bcb-11e6-854a-a9c2b6576268.png)

The photo then appears again in the event popup...

![image](https://cloud.githubusercontent.com/assets/25212/14837267/9f5d2894-0bcb-11e6-8fa3-f21dd613a112.png)

cc @amirad Thoughts? 

**Some thoughts** - I'd like to find a way to make the photo bigger in the popup, or at least have a way to expand it.
- Maybe it could pop up zoomed when clicked?
- Maybe add another tab to the photo where you can see it larger?

**Comment by amirad** [comment]
LOVE! It's perfect @flukeout 

I think maybe the pop up zoomed when clicked is a good idea.

**Comment by flukeout** [comment]
Making some progress here, especially in how the smaller image is zoomed... 

![images](https://cloud.githubusercontent.com/assets/25212/14894700/c9b78634-0d29-11e6-8f83-676649d5bbc3.gif)

**Comment by amirad** [comment]
YASSSS

**Comment by flukeout** [comment]
...QUEEN!!!

okay, i'll push the changes up so you can take a look!
