### ISSUE TITLE
Test with real report content

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/clubs-events#38]
Fill out some super long event reports. with real info. cc @amirad @flukeout 

I'm concerned about the height/layout.

**Comment by amirad** [comment]
@soapdog want to be the rockstar you are and write a super _long_ test report so we can see what happens?

**Comment by soapdog** [comment]
@xmatthewx and @amirad On Sunday we'll have two events which will generate real data for testing this new system. Can I wait till them or do you want me to fill reports from my previous events? I can do that as well...

**Comment by flukeout** [comment]
@soapdog Let's hang on until the real events. We'll be making some more changes to the reporting tool this week, so that might be safer. Thanks!

**Comment by soapdog** [comment]
@flukeout, perfect! will fill that form late on Sunday then

**Comment by flukeout** [comment]
Going to close this - as the testing will just happen.
