### ISSUE TITLE
Add Country via drop-down select

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/clubs-events#40]
To avoid typos.

might be helpful http://webapps.stackexchange.com/questions/76189/how-to-create-a-countries-drop-down-list-question-without-entering-all-countrie

**Comment by flukeout** [comment]
It's already a dropdown - were you looking at the "Editing the Form" view? It's not as obvious there...

![image](https://cloud.githubusercontent.com/assets/25212/14536783/0399f212-0229-11e6-8266-43212ab13309.png)

One question is - do we want to put certain countries first? It's a looong list, and you can't search.
