### ISSUE TITLE
Add Twitter handle or email addresses when submitting event report

### ISSUE THREAD

**Issue by amirad** [mozilla/clubs-events#41]
Just realized that there is no way to contact someone if want to follow-up about their event or if there is an issue with their submission. What do you think about asking for a twitter handle (this being optional) for others to see and asking for an email address (which is required) and we only see it?
@flukeout @xmatthewx

**Comment by flukeout** [comment]
I've added a "Your Contact Details" field and will display it on the event report detail page.

**Comment by amirad** [comment]
Perfect. thank you!

**Comment by xmatthewx** [comment]
I don't think we should gather email addresses in the form. We can't guarantee that info will remain private. A URL to any social media is safer.

**Comment by flukeout** [comment]
Okay I've got...

**Your Contact Details**
_Let use know one of your social media profiles so we can reach you._

Dunno.. what you think?

**Comment by amirad** [comment]
Let's ask specifically for twitter. Otherwise people share things like Facebook and I don't want myself or community members to have to reach out on that medium.

**Comment by flukeout** [comment]
Sounds good!

**Comment by flukeout** [comment]
Asking for a Twitter handle, but leaving it optional for those who don't have twitter.
