### ISSUE TITLE
Display links to curriculum

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/clubs-events#44]
Don't seem to show up. Also, I think URL validation in the form would be helpful. See:  http://mozilla.github.io/clubs-events/?event=13

**Comment by flukeout** [comment]
Let's chat re: links in our one on one. I'm wary of validating inputs, in case someone puts in several links or adds some text based context about what they used.

We could try to pull out links from the response when we display it though - i could look into that.

**Comment by flukeout** [comment]
Hmmm - this is a problem with my "valid URL checker" not reporting a positive. Looking into it.

**Comment by flukeout** [comment]
Okay, have improved thigns a bit where it finds links within the copy of the response, and converts them into clickable links, shown here...

![image](https://cloud.githubusercontent.com/assets/25212/14542635/d3ef8f06-0244-11e6-9f65-28848cd0cbd9.png)

**Comment by flukeout** [comment]
Fixsed
