### ISSUE TITLE
Feedback: A way to amend & edit the report.

### ISSUE THREAD

**Issue by flukeout** [mozilla/clubs-events#48]
From @soapdog 

> It would be cool if there was a way to amend the report later. For example, I am yet to write a blog post about this event but I will do it tonight. If there was a way to revisit the report to add links it would be great as future CCs might want the updated information.

Currently, we have a link that edits you edit the form immediately after you've submitted it, but have no way to make changes to your report later on.

If we stick with the current Google-spreadsheet-as-backend system, we could make the spreadsheet publicly editable and add a front-end for making edits. Not sure this is a good idea, as we would be putting our data at risk.

**Comment by soapdog** [comment]
Maybe we can have moderators do it manually. The CC opens an issue on github with the new data and we go there and change it.

On a side note to this, it would be great if the description field followed markdown rules. When I pasted my report there, I tried skipping lines to make paragraphs, which of course got removed by the system and now the report is quite hard to read...

**Comment by flukeout** [comment]
Yeah, we could totally do manual updates for now.

Agreed about the line breaks, the service we use to fetch the data (as JSON) from the spreadsheet strips the whitespace =( I've reached out to the project creator and he said he'd take a look at it. Anyway, I'm not sure we can wait for him to fix it. I'll file a separate issue for that.

**Comment by soapdog** [comment]
@flukeout feel free to CC me on any of those issues if you need help testing. We can be your guinea pig! :hamster:
