### ISSUE TITLE
Enable spreadsheet notifications to get notified when there are new responses.

### ISSUE THREAD

**Issue by flukeout** [mozilla/clubs-events#51]
@amirad and @carotejada you can get notified by email when someone submits a new event report. You can do it in the [spreadsheet](https://docs.google.com/spreadsheets/d/1QHl2bjBhMslyFzR5XXPzMLdzzx7oeSKTbgR5PM8qp64/edit#gid=1045576576) in the Tools dropdown under **Notification Rules**

![image](https://cloud.githubusercontent.com/assets/25212/14895035/82639528-0d2b-11e6-8448-1ed4adc6be04.png)

I just enabled mine and approved a report that was submitted a few days ago. I think it's important that we're prompt to approve stuff so that people feel encouraged and rewarded for adding them.

Cheers!

**Comment by amirad** [comment]
Done. Thanks @flukeout that's really helpful to know and totally agree with being prompt about approving.

**Comment by Carotejada** [comment]
Definitely helpful. Thank you @flukeout!
