### ISSUE TITLE
Make event reports easier to share

### ISSUE THREAD

**Issue by flukeout** [mozilla/clubs-events#53]
Feedback from regional coordinators via @amirad...
- They are unsure about how to share an event report on their blog, Twitter, or Facebook, for example
- Copying and pasting the URL (which loads up a specific event report) was not intuitive
- Event reports shared on Facebook appear plain and uninteresting

Lower priority
- Would like to be able to export the event report into a format that is usable on a blog
  - @amirad can you provide some clarity here, was the request for example to get some HTML to copy and paste into a blog platform or something different?

I'll work on...
- Some UX & UI ideas for sharing
  - Adding a share button that makes it easy to copy the URL?
  - Adding share buttons for specific social networks?
- Research what we need to do so that the best image available shows as a thumbnail when a report is shared

**Comment by amirad** [comment]
Thanks Luke! Keeping @jvallera in the thread here too in case she has anything else to add. 

I'm not sure about the blogging request, but I believe it was get the raw test to drop into a blogpost that can be shared elsewhere. 

Love the next steps to work on!
