### ISSUE TITLE
Make a clean version of this for others to use easily!

### ISSUE THREAD

**Issue by flukeout** [mozilla/clubs-events#9]
We can set up a repo that's easy to clone & configure once you set up your form and know the spreadsheet URL maybe? However, we rely on sheetsu, so that's a bad dependency to have - should look into using the native Google api like @davidascher has.

**Comment by xmatthewx** [comment]
This would be fab. For now, you might just organize your code to separate the core from things specific to this instance.

**Comment by flukeout** [comment]
Closing because who cares for now. Let's see if its useful first.
